#!/usr/bin/env sh

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"

if [ -s "$NVM_DIR/nvm.sh" ]; then
  # shellcheck disable=SC1090
  . "$NVM_DIR/nvm.sh"
fi

if [ -d "$NVM_DIR/versions/node" ]; then
  latest="$(ls -1 "$NVM_DIR/versions/node" | sort -V | tail -1)"
  export PATH="$NVM_DIR/versions/node/$latest/bin:$PATH"
fi

export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

npx lint-staged
